{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chart.fullname" . }}-ingress
  labels:
  {{- include "chart.labels" . | nindent 4 }}
  annotations:
{{ toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName | quote }}
  rules:
  - host: {{ .Values.ingress.host | quote }}
    http:
      paths:
      - backend:
          service:
            name: '{{ include "chart.fullname" . }}-service'
            port:
              number: 8081
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ .Values.ingress.host | quote }}
    secretName: {{ include "chart.fullname" . }}-tls
{{- end -}}
