{{- if .Values.route.enabled }}
apiVersion: {{ .Values.route.apiVersion | default "gateway.networking.k8s.io/v1" }}
kind: {{ .Values.route.kind | default "HTTPRoute" }}
metadata:
  name: {{ include "chart.fullname" . }}-route
  labels:
  {{- include "chart.labels" . | nindent 4 }}
  {{- with .Values.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.route.parentRefs }}
  parentRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.route.hostnames }}
  hostnames:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  rules:
    - backendRefs:
        - name: {{ include "chart.fullname" . }}-service
          port: 8081
      {{- with .Values.route.filters }}
      filters:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.route.matches }}
      matches:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
{{- end }}