apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-service
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: go-link-shortener
    {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
